"""updated-rooms-and-room-invitations

Revision ID: 1f4434654153
Revises: 31e6e86215ac
Create Date: 2025-06-17 12:02:49.328232

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1f4434654153"
down_revision: Union[str, None] = "31e6e86215ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_room_invitations",
        sa.Column(
            "admin_status",
            postgresql.ENUM(
                "pending",
                "accepted",
                "declined",
                "expired",
                "cancelled",
                name="invitation_status_enum",
                create_type=False,
            ),
            server_default="pending",
            nullable=False,
        ),
    )
    op.add_column(
        "chat_rooms",
        sa.Column(
            "allow_non_admin_invitations",
            sa.Boolean(),
            server_default="TRUE",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_rooms", "allow_non_admin_invitations")
    op.drop_column("chat_room_invitations", "admin_status")

    # ### end Alembic commands ###
