"""add chat_user_sessions

Revision ID: 268b111b3b66
Revises: 192ec2c14e4a
Create Date: 2025-06-01 12:35:30.379707

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "268b111b3b66"
down_revision: Union[str, None] = "192ec2c14e4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_user_sessions",
        sa.Column("user_id", sa.String(length=60), nullable=True),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column(
            "is_logged_out", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("logged_out_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["chat_users.id"],
            name=op.f("fk_chat_user_sessions_user_id_chat_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_user_sessions")),
    )
    op.create_index(
        op.f("ix_chat_user_sessions_created_at"),
        "chat_user_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_user_sessions_id"), "chat_user_sessions", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_chat_user_sessions_is_logged_out"),
        "chat_user_sessions",
        ["is_logged_out"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_user_sessions_session_id"),
        "chat_user_sessions",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_user_sessions_user_id"),
        "chat_user_sessions",
        ["user_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_chat_user_sessions_user_id"), table_name="chat_user_sessions"
    )
    op.drop_index(
        op.f("ix_chat_user_sessions_session_id"), table_name="chat_user_sessions"
    )
    op.drop_index(
        op.f("ix_chat_user_sessions_is_logged_out"), table_name="chat_user_sessions"
    )
    op.drop_index(op.f("ix_chat_user_sessions_id"), table_name="chat_user_sessions")
    op.drop_index(
        op.f("ix_chat_user_sessions_created_at"), table_name="chat_user_sessions"
    )
    op.drop_table("chat_user_sessions")
    # ### end Alembic commands ###
