"""added unique to chat_user_sessions.jti and session_id

Revision ID: 2e1599e80245
Revises: 268b111b3b66
Create Date: 2025-06-02 18:08:30.959029

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e1599e80245"
down_revision: Union[str, None] = "268b111b3b66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chat_user_sessions_session_id", table_name="chat_user_sessions")
    op.create_index(
        op.f("ix_chat_user_sessions_session_id"),
        "chat_user_sessions",
        ["session_id"],
        unique=True,
    )
    op.create_unique_constraint(
        op.f("uq_chat_user_sessions_jti"), "chat_user_sessions", ["jti"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_chat_user_sessions_jti"), "chat_user_sessions", type_="unique"
    )
    op.drop_index(
        op.f("ix_chat_user_sessions_session_id"), table_name="chat_user_sessions"
    )
    op.create_index(
        "ix_chat_user_sessions_session_id",
        "chat_user_sessions",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###
