"""added rooms, room_invitations, room_members

Revision ID: 31e6e86215ac
Revises: e72aa6ae1a28
Create Date: 2025-06-13 10:22:57.319281

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "31e6e86215ac"
down_revision: Union[str, None] = "e72aa6ae1a28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_type t
                    JOIN pg_enum e ON t.oid = e.enumtypid
                    WHERE t.typname = 'invitation_status_enum'
                ) THEN
                    CREATE TYPE invitation_status_enum AS ENUM ('pending', 'accepted', 'declined', 'expired', 'cancelled');
                END IF;
            END $$;
            """
        )
    )
    op.create_table(
        "chat_rooms",
        sa.Column("owner_id", sa.String(length=60), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("room_icon", sa.String(), nullable=True),
        sa.Column(
            "messages_delete_able", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column(
            "is_deactivated", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column(
            "allow_admin_messages_only",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        sa.Column("is_private", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["chat_users.id"],
            name=op.f("fk_chat_rooms_owner_id_chat_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_rooms")),
    )
    op.create_index(
        op.f("ix_chat_rooms_created_at"), "chat_rooms", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_chat_rooms_id"), "chat_rooms", ["id"], unique=True)
    op.create_index(op.f("ix_chat_rooms_name"), "chat_rooms", ["name"], unique=False)
    op.create_index(
        op.f("ix_chat_rooms_owner_id"), "chat_rooms", ["owner_id"], unique=False
    )
    op.create_table(
        "chat_room_invitations",
        sa.Column("room_id", sa.String(length=60), nullable=True),
        sa.Column("inviter_id", sa.String(length=60), nullable=True),
        sa.Column("invitee_id", sa.String(length=60), nullable=True),
        sa.Column(
            "invitation_status",
            postgresql.ENUM(
                "pending",
                "accepted",
                "declined",
                "expired",
                "cancelled",
                name="invitation_status_enum",
                create_type=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("expiration", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invitee_id"],
            ["chat_users.id"],
            name=op.f("fk_chat_room_invitations_invitee_id_chat_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["inviter_id"],
            ["chat_users.id"],
            name=op.f("fk_chat_room_invitations_inviter_id_chat_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["chat_rooms.id"],
            name=op.f("fk_chat_room_invitations_room_id_chat_rooms"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_room_invitations")),
        sa.UniqueConstraint(
            "room_id", "invitee_id", name="uq_room_invitation_room_id_invitee_id"
        ),
    )
    op.create_index(
        op.f("ix_chat_room_invitations_created_at"),
        "chat_room_invitations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_room_invitations_id"),
        "chat_room_invitations",
        ["id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_chat_room_invitations_invitee_id"),
        "chat_room_invitations",
        ["invitee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_room_invitations_inviter_id"),
        "chat_room_invitations",
        ["inviter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_room_invitations_room_id"),
        "chat_room_invitations",
        ["room_id"],
        unique=False,
    )
    op.create_table(
        "chat_room_members",
        sa.Column("member_id", sa.String(length=60), nullable=True),
        sa.Column("room_id", sa.String(length=60), nullable=True),
        sa.Column("is_admin", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("left_room", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["chat_users.id"],
            name=op.f("fk_chat_room_members_member_id_chat_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["chat_rooms.id"],
            name=op.f("fk_chat_room_members_room_id_chat_rooms"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_room_members")),
        sa.UniqueConstraint(
            "room_id", "member_id", name="uq_room_member_room_id_user_id"
        ),
    )
    op.create_index(
        op.f("ix_chat_room_members_created_at"),
        "chat_room_members",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_room_members_id"), "chat_room_members", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_chat_room_members_member_id"),
        "chat_room_members",
        ["member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_room_members_room_id"),
        "chat_room_members",
        ["room_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_chat_room_members_room_id"), table_name="chat_room_members")
    op.drop_index(
        op.f("ix_chat_room_members_member_id"), table_name="chat_room_members"
    )
    op.drop_index(op.f("ix_chat_room_members_id"), table_name="chat_room_members")
    op.drop_index(
        op.f("ix_chat_room_members_created_at"), table_name="chat_room_members"
    )
    op.drop_table("chat_room_members")
    op.drop_index(
        op.f("ix_chat_room_invitations_room_id"), table_name="chat_room_invitations"
    )
    op.drop_index(
        op.f("ix_chat_room_invitations_inviter_id"), table_name="chat_room_invitations"
    )
    op.drop_index(
        op.f("ix_chat_room_invitations_invitee_id"), table_name="chat_room_invitations"
    )
    op.drop_index(
        op.f("ix_chat_room_invitations_id"), table_name="chat_room_invitations"
    )
    op.drop_index(
        op.f("ix_chat_room_invitations_created_at"), table_name="chat_room_invitations"
    )
    op.drop_table("chat_room_invitations")
    op.drop_index(op.f("ix_chat_rooms_owner_id"), table_name="chat_rooms")
    op.drop_index(op.f("ix_chat_rooms_name"), table_name="chat_rooms")
    op.drop_index(op.f("ix_chat_rooms_id"), table_name="chat_rooms")
    op.drop_index(op.f("ix_chat_rooms_created_at"), table_name="chat_rooms")
    op.drop_table("chat_rooms")
    # ### end Alembic commands ###
