"""updated users.email length

Revision ID: 7b9bcdd6e89c
Revises: 2e1599e80245
Create Date: 2025-06-04 13:38:55.768166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b9bcdd6e89c"
down_revision: Union[str, None] = "2e1599e80245"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_users",
        "first_name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "chat_users",
        "last_name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "chat_users",
        "email",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=150),
        existing_nullable=False,
    )
    op.alter_column(
        "chat_users",
        "username",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=150),
        existing_nullable=True,
    )
    op.alter_column(
        "chat_users",
        "idempotency_key",
        existing_type=sa.VARCHAR(length=120),
        type_=sa.String(length=150),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_users",
        "idempotency_key",
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=120),
        existing_nullable=False,
    )
    op.alter_column(
        "chat_users",
        "username",
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=30),
        existing_nullable=True,
    )
    op.alter_column(
        "chat_users",
        "email",
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "chat_users",
        "last_name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=30),
        existing_nullable=True,
    )
    op.alter_column(
        "chat_users",
        "first_name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=30),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
