"""updated rmmo-messages

Revision ID: 7cf0e37bfb10
Revises: 1f4434654153
Create Date: 2025-06-28 03:58:59.508450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7cf0e37bfb10"
down_revision: Union[str, None] = "1f4434654153"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_room_messages",
        sa.Column("sender_id", sa.String(length=60), nullable=True),
        sa.Column("room_id", sa.String(length=60), nullable=True),
        sa.Column("parent_message_id", sa.String(length=60), nullable=True),
        sa.Column("content", sa.TEXT(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "delivered", "sent", name="message_status_enum", create_type=False
            ),
            server_default="sent",
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("media_url", sa.String(), nullable=True),
        sa.Column("media_type", sa.String(), server_default="text", nullable=False),
        sa.Column("is_edited", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_message_id"],
            ["chat_room_messages.id"],
            name=op.f("fk_chat_room_messages_parent_message_id_chat_room_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["chat_rooms.id"],
            name=op.f("fk_chat_room_messages_room_id_chat_rooms"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["chat_users.id"],
            name=op.f("fk_chat_room_messages_sender_id_chat_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_room_messages")),
    )
    op.create_index(
        op.f("ix_chat_room_messages_created_at"),
        "chat_room_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_room_messages_id"), "chat_room_messages", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_chat_room_messages_parent_message_id"),
        "chat_room_messages",
        ["parent_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_room_messages_room_id"),
        "chat_room_messages",
        ["room_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_room_messages_sender_id"),
        "chat_room_messages",
        ["sender_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_chat_room_messages_sender_id"), table_name="chat_room_messages"
    )
    op.drop_index(
        op.f("ix_chat_room_messages_room_id"), table_name="chat_room_messages"
    )
    op.drop_index(
        op.f("ix_chat_room_messages_parent_message_id"), table_name="chat_room_messages"
    )
    op.drop_index(op.f("ix_chat_room_messages_id"), table_name="chat_room_messages")
    op.drop_index(
        op.f("ix_chat_room_messages_created_at"), table_name="chat_room_messages"
    )
    op.drop_table("chat_room_messages")
    # ### end Alembic commands ###
