"""initial migration

Revision ID: 192ec2c14e4a
Revises:
Create Date: 2025-05-31 11:13:41.838913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "192ec2c14e4a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_users",
        sa.Column("first_name", sa.String(length=30), nullable=True),
        sa.Column("last_name", sa.String(length=30), nullable=True),
        sa.Column("email", sa.String(length=30), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=True),
        sa.Column("username", sa.String(length=30), nullable=True),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column(
            "email_verified", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("profile_photo", sa.String(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "active", "inactive", "deleted", "banned", name="user_status_enum"
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "online_status",
            postgresql.ENUM(
                "online", "away", "offline", name="user_online_status_enum"
            ),
            server_default="online",
            nullable=False,
        ),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_users")),
        sa.UniqueConstraint("email", name=op.f("uq_chat_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_chat_users_username")),
    )
    op.create_index(
        op.f("ix_chat_users_created_at"), "chat_users", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_chat_users_id"), "chat_users", ["id"], unique=True)
    op.create_index(
        "uq_chat_users_idempotency_key", "chat_users", ["idempotency_key"], unique=True
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_chat_users_idempotency_key", table_name="chat_users")
    op.drop_index(op.f("ix_chat_users_id"), table_name="chat_users")
    op.drop_index(op.f("ix_chat_users_created_at"), table_name="chat_users")
    op.drop_table("chat_users")
    # ### end Alembic commands ###
