"""initial migrations

Revision ID: 929e7184f6b5
Revises: 
Create Date: 2024-10-09 14:57:03.569428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.base.enums import *

# revision identifiers, used by Alembic.
revision: str = '929e7184f6b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('status', user_status_enum, server_default='active', nullable=False),
    sa.Column('online_status', user_online_status_enum, server_default='online', nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_users_idempotency_key')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username')),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_users_created_at'), 'users', ['created_at'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_users_id'), 'users', ['id'], unique=False, schema='chat')
    op.create_table('profiles',
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('recovery_email', sa.String(), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('profession', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('avatar_url', sa.String(length=200), nullable=True),
    sa.Column('facebook_link', sa.String(length=200), nullable=True),
    sa.Column('x_link', sa.String(length=200), nullable=True),
    sa.Column('instagram_link', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_profiles_created_at'), 'profiles', ['created_at'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_profiles_id'), 'profiles', ['id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_profiles_user_id'), 'profiles', ['user_id'], unique=True, schema='chat')
    op.create_table('rooms',
    sa.Column('room_name', sa.String(length=130), nullable=False),
    sa.Column('creator_id', sa.String(length=60), nullable=False),
    sa.Column('room_type', room_type_enum, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('messages_deletable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['chat.users.id'], name=op.f('fk_rooms_creator_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_rooms_created_at'), 'rooms', ['created_at'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_rooms_creator_id'), 'rooms', ['creator_id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_rooms_id'), 'rooms', ['id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_rooms_idempotency_key'), 'rooms', ['idempotency_key'], unique=True, schema='chat')
    op.create_table('socialregisters',
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('sub', sa.String(length=60), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('id_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], name=op.f('fk_socialregisters_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_socialregisters')),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_socialregisters_created_at'), 'socialregisters', ['created_at'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_socialregisters_id'), 'socialregisters', ['id'], unique=False, schema='chat')
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('room_id', sa.String(length=60), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('chat_type', chat_type_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat.rooms.id'], name=op.f('fk_messages_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], name=op.f('fk_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'messages', ['created_at'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_messages_id'), 'messages', ['id'], unique=True, schema='chat')
    op.create_index(op.f('ix_chat_messages_room_id'), 'messages', ['room_id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_messages_user_id'), 'messages', ['user_id'], unique=False, schema='chat')
    op.create_table('roominvitations',
    sa.Column('room_id', sa.String(length=60), nullable=False),
    sa.Column('inviter_id', sa.String(length=60), nullable=False),
    sa.Column('invitee_id', sa.String(length=60), nullable=False),
    sa.Column('room_type', room_type_enum, nullable=False),
    sa.Column('invitation_status', invitation_status_enum, server_default='pending', nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['chat.users.id'], name=op.f('fk_roominvitations_invitee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['chat.users.id'], name=op.f('fk_roominvitations_inviter_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['chat.rooms.id'], name=op.f('fk_roominvitations_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roominvitations')),
    sa.UniqueConstraint('room_id', 'invitee_id', name='uq_room_invitation_room_id_invitee_id'),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_roominvitations_created_at'), 'roominvitations', ['created_at'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_roominvitations_id'), 'roominvitations', ['id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_roominvitations_invitee_id'), 'roominvitations', ['invitee_id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_roominvitations_inviter_id'), 'roominvitations', ['inviter_id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_roominvitations_room_id'), 'roominvitations', ['room_id'], unique=False, schema='chat')
    op.create_table('roommembers',
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('room_id', sa.String(length=60), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('room_type', room_type_enum, nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat.rooms.id'], name=op.f('fk_roommembers_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], name=op.f('fk_roommembers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roommembers')),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_room_member_room_id_user_id'),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_roommembers_created_at'), 'roommembers', ['created_at'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_roommembers_id'), 'roommembers', ['id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_roommembers_idempotency_key'), 'roommembers', ['idempotency_key'], schema='chat')
    op.create_index(op.f('ix_chat_roommembers_room_id'), 'roommembers', ['room_id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_roommembers_user_id'), 'roommembers', ['user_id'], unique=False, schema='chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_roommembers_user_id'), table_name='roommembers', schema='chat')
    op.drop_index(op.f('ix_chat_roommembers_room_id'), table_name='roommembers', schema='chat')
    op.drop_index(op.f('ix_chat_roommembers_id'), table_name='roommembers', schema='chat')
    op.drop_index(op.f('ix_chat_roommembers_created_at'), table_name='roommembers', schema='chat')
    op.drop_table('roommembers', schema='chat')
    op.drop_index(op.f('ix_chat_roominvitations_room_id'), table_name='roominvitations', schema='chat')
    op.drop_index(op.f('ix_chat_roominvitations_inviter_id'), table_name='roominvitations', schema='chat')
    op.drop_index(op.f('ix_chat_roominvitations_invitee_id'), table_name='roominvitations', schema='chat')
    op.drop_index(op.f('ix_chat_roominvitations_id'), table_name='roominvitations', schema='chat')
    op.drop_index(op.f('ix_chat_roominvitations_created_at'), table_name='roominvitations', schema='chat')
    op.drop_table('roominvitations', schema='chat')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='messages', schema='chat')
    op.drop_index(op.f('ix_chat_messages_room_id'), table_name='messages', schema='chat')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='messages', schema='chat')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='messages', schema='chat')
    op.drop_table('messages', schema='chat')
    op.drop_index(op.f('ix_chat_socialregisters_id'), table_name='socialregisters', schema='chat')
    op.drop_index(op.f('ix_chat_socialregisters_created_at'), table_name='socialregisters', schema='chat')
    op.drop_table('socialregisters', schema='chat')
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='rooms', schema='chat')
    op.drop_index(op.f('ix_chat_rooms_creator_id'), table_name='rooms', schema='chat')
    op.drop_index(op.f('ix_chat_rooms_created_at'), table_name='rooms', schema='chat')
    op.drop_table('rooms', schema='chat')
    op.drop_index(op.f('ix_chat_profiles_user_id'), table_name='profiles', schema='chat')
    op.drop_index(op.f('ix_chat_profiles_id'), table_name='profiles', schema='chat')
    op.drop_index(op.f('ix_chat_profiles_created_at'), table_name='profiles', schema='chat')
    op.drop_table('profiles', schema='chat')
    op.drop_index(op.f('ix_chat_users_id'), table_name='users', schema='chat')
    op.drop_index(op.f('ix_chat_users_created_at'), table_name='users', schema='chat')
    op.drop_table('users', schema='chat')

    # ### end Alembic commands ###
