"""updated users.username, users.email, and users.idempotency_key to have a unique constraint

Revision ID: b3a7d33761f9
Revises: 40bad290897a
Create Date: 2024-09-24 12:01:39.608659

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b3a7d33761f9'
down_revision: Union[str, None] = '40bad290897a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], schema='public')
    op.create_unique_constraint(op.f('uq_users_idempotency_key'), 'users', ['idempotency_key'], schema='public')
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', schema='public', type_='unique')
    op.drop_constraint(op.f('uq_users_idempotency_key'), 'users', schema='public', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', schema='public', type_='unique')
    # ### end Alembic commands ###
