"""added profiles.gender, profiles.DOB

Revision ID: fa3480f158bc
Revises: 25f31d9f40f9
Create Date: 2024-10-06 18:00:35.397758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3480f158bc'
down_revision: Union[str, None] = '25f31d9f40f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles',
                  sa.Column('gender', sa.String(length=20), nullable=True),
                  schema="chat"
    )
    op.add_column('profiles',
                  sa.Column('DOB', sa.Date(), nullable=True),
                  schema='chat'
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'gender', schema='chat')
    op.drop_column('profiles', 'DOB', schema='chat')
    # ### end Alembic commands ###
